spring.autoconfigure.exclude=
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/degree_planner
spring.datasource.username=degree_planner
spring.datasource.password=degree_planner
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true
